paths:
  uploads: public/uploads
  static: public
collections_config:
  # pages:
  #   path: src/content/docs
  #   name: Pages
  #   icon: wysiwyg
  #   disable_add: false
  #   disable_add_folder: false
  #   disable_file_actions: false
  guides:
    path: src/content/docs/guides
    name: Guides
    icon: files
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  reference:
    path: src/content/docs/reference
    name: Reference
    icon: difference
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Asia/Saigon
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
